logging:
  level:
    org.springframework.web.socket: TRACE
    org.springframework.messaging: TRACE

server:
  config:
    activate:
      on-profile: local

spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb

  jwt:
    secret: ${SECRET_KEY}
    accessTokenExpiration: ${ACCESS_TOKEN_EXPIRATION}
    refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: true



  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: ${GOOGLE_AUTHORIZATION_GRANT_TYPE}
            scope:
              - profile
              - email

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
            client-authentication-method: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
            scope:
              - profile_nickname
              - profile_image
              - account_email

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: ${NAVER_AUTHORIZATION_GRANT_TYPE}
            scope:
              - name
              - email
              - profile_image

app:
  auth:
    redirectUri: ${APP_AUTH_REDIRECT_URI}

