version: '3.8'

services:
  spring-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-dev
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - /home/ubuntu/app/log:/log
    networks:
      - backend
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    volumes:
      - ../redis-data:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis-data: