version: '3.8'

services:
  frontend:
    image: frontend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: frontend
    volumes:
      - /var/www/html/:/app/dist
    ports:
      - "5173:5173"
    networks:
      - frontend
    restart: unless-stopped


networks:
  frontend:
    driver: bridge