version: '3.8'

services:
  frontend:
    image: frontend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: frontend
    volumes:
      - /var/www/html:/var/www/html
    networks:
      - frontend
    restart: "no"

networks:
  frontend:
    driver: bridge