version: '3.8'

services:
  frontend:
    image: frontend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: frontend
    volumes:
      - frontend_build:/app/dist
    networks:
      - frontend
    restart: unless-stopped


networks:
  frontend:
    driver: bridge