version: '3.8'

services:
  react-app-dev:
    image: frontend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - frontend
    restart: unless-stopped


networks:
  frontend:
    driver: bridge